name: Update dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  taze:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
      - name: Check updates
        id: taze
        run: bun x -b taze -a --failOnOutdated
        working-directory: frontend
        continue-on-error: true
      - name: Updates dependencies
        working-directory: frontend
        if: steps.taze.outcome == 'failure'
        run: bun x -b taze -w
      - name: Commit changes
        working-directory: frontend
        if: steps.taze.outcome == 'failure'
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add package.json
          git commit -m 'chore(deps): update dependencies'
          git push
